/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge_aws.db;


import com.kbalazsworks.stackjudge_aws.db.tables.RemoteFiles;
import com.kbalazsworks.stackjudge_aws.db.tables.records.RemoteFilesRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<RemoteFilesRecord> REMOTE_FILES_PKEY = Internal.createUniqueKey(RemoteFiles.REMOTE_FILES, DSL.name("remote_files_pkey"), new TableField[] { RemoteFiles.REMOTE_FILES.ID }, true);
}
