/*
 * This file is generated by jOOQ.
 */
package com.kbalazsworks.stackjudge_aws.db;


import com.kbalazsworks.stackjudge_aws.db.tables.RemoteFiles;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.remote_files</code>.
     */
    public static final RemoteFiles REMOTE_FILES = RemoteFiles.REMOTE_FILES;
}
